name: CI

concurrency:
  cancel-in-progress: true
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    uses: ppizarror/workflow-actions/.github/workflows/test_python.yml@master
    strategy:
      matrix:
        python: [ 3.8, 3.9, '3.10', '3.11', '3.12' ]
    with:
      install-extras: test
      os: ubuntu-latest
      python-version: ${{ matrix.python}}

  codeql:
    uses: ppizarror/workflow-actions/.github/workflows/codeql.yml@master
    with:
      language: python